name: 'Auto-merge Main Branch Into Pull Requests'
description: 'This action will helps your organization by automatically merging new commits to your main branch into open Pull Requests'
author: 'Jonathan Sibley'
inputs:
  githubToken:
    required: true
    description: 'a scoped Github token which the action will use to run on your Pull Requests. See the following for an example: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-1-passing-the-github_token-as-an-input'
    default: 'main'
  waitMilliseconds:
    required: false
    description: 'an optional forced wait time (in milliseconds) before this action runs'
    default: '0'
  mainBranchName:
    required: false
    description: 'the name of the main branch for your repo'
    default: 'main'
  onlyMergeMainForDraftPullRequests:
    required: false
    description: 'set to `true` if you would like this action to only run on Pull Requests in the Draft state'
    default: 'false'
  onlyMergeBranchesWithPrefixes:
    required: false
    description: 'an optional comma-separated list of branch name prefixes. This action will only run on Pull Requests whose branch names start with one of these prefixes.'
    default: 'false'
  onlyPullRequestsWithLabels:
    required: false
    description: 'an optional comma-separated list of Pull Request labels required for this action to run on a given Pull Request'
    default: 'false'
  skipPullRequestsWithLabels:
    required: false
    description: 'an optional comma-separated list of Pull Request labels which, when present, will prevent this action from running'
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
